// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Ossy1717

//@version=4
study("(Study) RSI + STOCH Overb/s", overlay = true)

// Inputs //
tradeDirection = input(defval = "All", title = "Long, Short or All Setups?", options = ["All", "Longs", "Shorts"])
stochLen = input(14, minval = 1, title = "Stoch Length")
periodK = input(3, title="K", minval=1)
periodD = input(3, title="D", minval=1)
rsiLen = input(14, minval = 1, title = "RSI Length")
rsiOverbought = input(defval = 70, title = "RSI Overbought", minval = 1, maxval = 100, step = 1)
rsiOversold = input(defval = 30, title = "RSI Oversold", minval = 1, maxval = 100, step = 1)
// Inputs //

// RSI
rsi = rsi(close, rsiLen)
// Stoch 
stk = sma(stoch(close, high, low, stochLen), 3)
k = sma(stoch(rsi, rsi, rsi, stochLen), periodK) // Blue
d = sma(k, periodD)

// Conditions
isRSIOverbought = rsi >= rsiOverbought
isRSIOversold = rsi <= rsiOversold
isStochOverbought = k >= rsiOverbought and d >= rsiOverbought
isStochOversold = k <= rsiOversold and d <= rsiOversold
goLong = isRSIOversold and isStochOversold and (tradeDirection == "All" or tradeDirection == "Longs")
goShort = isRSIOverbought and isStochOverbought and (tradeDirection == "All" or tradeDirection == "Shorts")

// Visuals
// RSI Debug //
// label.new(bar_index, goLong ? low : high, yloc = goLong ? yloc.belowbar : yloc.abovebar, text=tostring(rsi, '#'), textcolor=color.white, color = color.green, style = goLong ? label.style_label_up : label.style_label_down, size = size.small)
// RSI Debug //
if(goLong)
	label.new(x = bar_index, y = low, yloc = yloc.belowbar, text="OS", textcolor=color.white, color = color.green, style = label.style_label_up, size = size.small)
if(goShort)
	label.new(x = bar_index, y = high, yloc = yloc.abovebar, text="OB", textcolor=color.white, color = color.red, style = label.style_label_down, size = size.small)

// Alerts
alertcondition(goLong, title='Buy Signal', message='')
alertcondition(goShort, title='Sell Signal', message='')

    